
sudo: required
language: java

jdk:
  - openjdk8
  - oraclejdk9

# Below this line is configuration for deploying to the Sonatype OSS repo


script:
  - mvn clean cobertura:cobertura -Dtest=ObjectReaderTest#testParserFeatures -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/jackson-databind/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "KFFxtTh1FptOL32R6X1dgjGM0zePIGlecD2F28+74sy5KZYpcU33ig/Le+lPsaFPG3Mbx9AVAgFhX7MtcP+dTrBmcOvT5CzehRH/62sXapOvdtvsWT+BA0hurHAqNjoRYlV7TP/VZuUxhrAgXkiXlA8yBI+ufHXL16/fLY0+IRLssWyjCZFB4fqgrvsIiutau5iUxH7Sez8XjH9folET5tsRkysvqf3rd8gsLe+qQBVsvtGT+XcD7jgY+5rsSfC0SV8k6kUCqgJfNDlEQu9vlKRJx2fWi85kHOOBvFU8a3ILmQmcgusMFYcnqTnYpi5ImpY0z/W5/vArcWa8VvB0k9Cld0OS/3Sy7w2FemduZunp9sUXKeZho/0t9JISQSNgr72hj/YR5Ib/I2/5NjUoVXnA2t+4Q2eKGXYnh3H+S1YtGD4NdVNNSt4k0zQXDyW83IKq3XS0nvbHPuN61tFRzdnylyQyUnE63FDclvSztEUvELFswuf+cP4nGFjrGHNSoeCmEBPJak7urrY30rHCk/NB+NHdo3piFf7x0BKmKUdA04kOvwteaJvMrm3B5un0B9KLTyiFfkHdIDOqBDl2TY+mbWqSRNpPVCVrO9P0kbztKKzPy7V6YwjbI2fJu0SHEJTZMMnF61QLlRNUQ0IgKEcx/9go9FpG1zOd6XZdmw0="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
